export const text = [
  `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
  `It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).`,
  `Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.`,
  `There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.`,
  `Sed vehicula, erat et molestie elementum, tellus massa vestibulum dui, vitae tempor elit odio a urna. Pellentesque pretium justo a eros maximus, nec porta velit elementum. Integer consequat pharetra mauris, eu tincidunt tellus elementum id. Praesent volutpat efficitur ligula at ultrices. Duis in dolor eu erat varius pellentesque. Aliquam sem ante, tempor ut aliquet pretium, condimentum vitae risus. Mauris interdum lectus sed dui ultricies, sit amet hendrerit leo fermentum. Integer vel felis mattis, consequat nulla a, egestas quam. Etiam vestibulum congue vestibulum. Morbi eros nisi, commodo suscipit lorem nec, porta pretium tellus.`,
  `Duis pharetra fringilla pretium. Curabitur a tortor in sem tristique ultricies. Nullam sagittis ligula non convallis dignissim. Morbi tellus dolor, facilisis eget porttitor sit amet, venenatis eu sem. Cras ullamcorper lectus venenatis auctor tempus. Curabitur eget nisl efficitur, pretium erat id, varius libero. Donec tempus justo sollicitudin eros maximus commodo quis at est. Mauris nec sapien eros. Nunc tincidunt sapien id sem tincidunt, at finibus ligula posuere. Phasellus ipsum elit, egestas vel quam vitae, finibus luctus libero. Aenean et ante a turpis feugiat commodo sit amet eu magna. In vitae dapibus magna.`,
  `Integer a eros diam. Nam non metus nec lectus maximus mattis. Sed ultricies sodales tempus. Aenean eu enim sed magna bibendum egestas. Donec commodo vestibulum ligula, vitae sodales nisl malesuada id. Quisque risus ante, pulvinar non sodales non, vehicula vitae ante. Praesent vestibulum, eros eget feugiat suscipit, dolor lectus gravida dui, in condimentum neque quam ut ipsum. Vestibulum non lectus auctor, consectetur massa sit amet, ultrices urna. Suspendisse vulputate erat nunc, cursus convallis velit tempor ac.`,
  `Aliquam at ante dolor. Quisque nec metus sed nulla cursus blandit id sit amet libero. Mauris leo eros, ornare id nisl mollis, tincidunt auctor velit. Duis efficitur accumsan iaculis. In hac habitasse platea dictumst. Duis interdum gravida ornare. Nulla egestas eget erat vel mollis. Vivamus mattis, tellus vitae commodo ornare, sem urna vulputate ante, nec venenatis eros quam at lacus. Quisque gravida, neque ut eleifend consectetur, augue ex sodales sapien, eget ultrices nisl quam posuere justo.`,
  `Eu augue ut lectus arcu bibendum at varius vel pharetra. Feugiat nibh sed pulvinar proin gravida. Augue mauris augue neque gravida. Volutpat diam ut venenatis tellus in metus vulputate. Vestibulum morbi blandit cursus risus. Tellus id interdum velit laoreet id donec ultrices tincidunt arcu. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget egestas. Nullam eget felis eget nunc lobortis mattis. Pulvinar sapien et ligula ullamcorper malesuada proin libero. Volutpat ac tincidunt vitae semper quis lectus nulla at. Augue lacus viverra vitae congue eu. Commodo nulla facilisi nullam vehicula ipsum a arcu. Sed vulputate odio ut enim blandit volutpat maecenas. Neque egestas congue quisque egestas diam.`,
  `Semper risus in hendrerit gravida rutrum quisque non tellus orci. Nisl tincidunt eget nullam non. Eget aliquet nibh praesent tristique magna sit amet purus gravida. Dignissim cras tincidunt lobortis feugiat vivamus at. Fusce ut placerat orci nulla pellentesque dignissim enim sit amet. Tempus imperdiet nulla malesuada pellentesque elit eget gravida. Congue nisi vitae suscipit tellus mauris. Nisl pretium fusce id velit ut tortor pretium viverra. Bibendum neque egestas congue quisque egestas diam. Ut tortor pretium viverra suspendisse potenti nullam ac tortor. In ante metus dictum at tempor commodo ullamcorper a.`,
];
